excluded:
    - Tuist
    
line_length:
    - 120
    - 140
    
disabled_rules:
    - nesting
    - control_statement
    - trailing_whitespace
    - vertical_whitespace
    - vertical_parameter_alignment
    - cyclomatic_complexity
    - void_function_in_ternary
    - comment_spacing
    - function_parameter_count
    - type_name
    - closure_parameter_position
    - identifier_name
    - function_body_length

opt_in_rules:
    - empty_string
    - sorted_imports
